---
title: "nucella_growth"
author: "Tena Dhayalan"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning=FALSE, 
                      message=FALSE)
```

## Loading libraries 
```{r}
library(dplyr)
library(broom)
library(purrr)
library(lubridate)
library(tidyverse)
library(nlstools)
library(here)
library(stringr)

```

## Load datasets 

```{r}
shell <- read_csv(here("Data","afdw","nucella_afdw.csv"))
nucella <-  read_csv(here("Data","nucella_initial.csv"))
shell <- shell %>%
  left_join(nucella, by= c("snail_ID"))
```

### plot shell growth
```{r}
ggplot(data=shell, aes(x=pH, y=(shell_growth/dry_weight), group = interaction(pH, temp), color=as.factor(temp)))+
  geom_boxplot(outlier.shape=NA) +
  geom_point()+
  theme_bw() +
  theme(strip.background = element_rect(fill = "white"))+
  scale_color_manual(values=c("salmon", "salmon4"))+
  labs(x = "pH",
       color = "Temperature",
       y = "Shell growth (cm)")
```

### plot growth
```{r}
ggplot(data=shell, aes(x=pH, y=(shell_growth/dry_weight), group = interaction(pH, temp), color=as.factor(temp)))+
  geom_boxplot(outlier.shape=NA) +
  geom_point()+
  theme_bw() +
  theme(strip.background = element_rect(fill = "white"))+
  scale_color_manual(values=c("salmon", "salmon4"))+
  labs(x = "pH",
       color = "Temperature",
       y = "Shell growth (cm)")
```