
---
title: "predation"
author: "Tena Dhayalan"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning=FALSE, 
                      message=FALSE)
```

## Loading libraries 
```{r}
library(dplyr)
library(broom)
library(purrr)
library(lubridate)
library(tidyverse)
library(nlstools)
library(here)
library(stringr)

```

## Load datasets 

```{r}
mussel <- read_csv(here("Data","mytilus_mortality.csv"))
metadata <- read_csv(here("Data", "PR_2024", "Metadata.csv"))
predation <- mussel %>%
  filter(eaten=="Y")
```

### Plot
```{r}
ggplot(data=predation, aes(x = tank, fill = as.factor(pH)))+
  geom_histogram(bins = 30, color = "black", alpha = 0.7, position = "identity") +
  theme_bw() +
  theme(strip.background = element_rect(fill = "white"))+
  labs(x = "tank",
       color = "Temperature",
       y = "Number of predation events")
```

```{r}
mussel$eaten <- factor(mussel$eaten, levels = c("N", "Y"))  
model <- glm(eaten ~ pH * temp, data = mussel, family = binomial)

# View summary
summary(model)
```